version: '3.8'

services:
  cirtuo-rps-api:
    image: cirtuo-rps-api:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    depends_on:
      - cirtuo-rps-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      
  cirtuo-rps-db:
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cirtuo-rps-db